<?php $this->widget('ext.easyui.EasyuiGrid',array(
		'title'=>Yii::t('project','List NewsCate'),
		'url'=>Yii::app()->createUrl('newscate/loadData'),
		'model'=>'NewsCate',
		'idField'=>'cat_id',
		'htmlOptions'=>array(
			'method'=>'POST',
			'width'=>1250,
			'height'=>630,
		//	'idField'=>'good_id',
			'fitColumns'=>true,
			'nowrap'=>false,
			'rownumbers'=>true,
			'showFooter'=>true,
			'pagination'=>true,
			'rownumbers'=>false,
                        'singleSelect'=>false,
		),
		'toolbar_show'=>array(
			'add'=>array('href'=>Yii::app()->createUrl('newscate/create'),'text'=>'添加新闻分类'),
			'delete'=>array('href'=>Yii::app()->createUrl('newscate/delete'),'text'=>'删除新闻分类'),
			'edit'=>array('href'=>Yii::app()->createUrl('newscate/update')),
			'view'=>array('href'=>Yii::app()->createUrl('newscate/view')),
			'search'=>array('href'=>Yii::app()->createUrl('newscate/loadData'),'text'=>'搜索新闻分类','formTpl'=>'searchNewsCate'),
                        'multiple'=>array('href'=>Yii::app()->createUrl('newscate/updateBatch'),'text'=>'批量更改','formTpl'=>'multipleNewsCate'),
		),
		'columns'=>array(
                        array('field'=>'cat_id','title'=>Yii::t('project',NewsCate::model()->getAttributeLabel('cat_id')),'width'=>80,'checkbox'=>true),
                      //  array('field'=>'good_id','title'=>Yii::t('webshop',Goods::model()->getAttributeLabel('good_id')),'width'=>80),
			array('field'=>'cat_name','title'=>Yii::t('project',NewsCate::model()->getAttributeLabel('cat_name')),'width'=>100,'search'=>true),
                        array('field'=>'cat_alia','title'=>Yii::t('project',NewsCate::model()->getAttributeLabel('cat_alia')),'width'=>30,'search'=>true),
                        array('field'=>'sort_order','title'=>Yii::t('project',NewsCate::model()->getAttributeLabel('sort_order')),'width'=>100,'search'=>true),
		),
	));?>
