<?php $this->widget('ext.easyui.EasyuiGrid',array(
		'title'=>Yii::t('project','List Cates'),
		'url'=>Yii::app()->createUrl('cate/loadData'),
		'model'=>'Cate',
		'idField'=>'cat_id',
		'htmlOptions'=>array(
			'method'=>'POST',
			'width'=>1250,
			'height'=>630,
		//	'idField'=>'good_id',
			'fitColumns'=>true,
			'nowrap'=>false,
			'rownumbers'=>true,
			'showFooter'=>true,
			'pagination'=>true,
			'rownumbers'=>false,
                        'singleSelect'=>false,
		),
		'toolbar_show'=>array(
			'add'=>array('href'=>Yii::app()->createUrl('cate/create'),'text'=>'添加分类'),
			'delete'=>array('href'=>Yii::app()->createUrl('cate/delete'),'text'=>'删除分类'),
			'edit'=>array('href'=>Yii::app()->createUrl('cate/update')),
			'view'=>array('href'=>Yii::app()->createUrl('cate/view')),
			'search'=>array('href'=>Yii::app()->createUrl('cate/loadData'),'text'=>'搜索分类','formTpl'=>'searchCate'),
                        'multiple'=>array('href'=>Yii::app()->createUrl('cate/updateBatch'),'text'=>'批量更改','formTpl'=>'multipleCate'),
		),
		'columns'=>array(
                        array('field'=>'cat_id','title'=>Yii::t('webshop',Cate::model()->getAttributeLabel('cat_id')),'width'=>80,'checkbox'=>true),
                      //  array('field'=>'good_id','title'=>Yii::t('webshop',Goods::model()->getAttributeLabel('good_id')),'width'=>80),
			array('field'=>'cat_name','title'=>Yii::t('webshop',Cate::model()->getAttributeLabel('cat_name')),'width'=>200,'search'=>true),
                        array('field'=>'cat_desc','title'=>Yii::t('webshop',Cate::model()->getAttributeLabel('cat_desc')),'width'=>80,'search'=>true),
                        array('field'=>'sort_order','title'=>Yii::t('webshop',Cate::model()->getAttributeLabel('sort_order')),'width'=>80,'search'=>true),
		),
	));?>
