<?php $this->widget('ext.easyui.EasyuiGrid',array(
		'title'=>Yii::t('webshop','Goods Cate'),
		'url'=>Yii::app()->createUrl('webshop/goodscate/loadData'),
		'model'=>'GoodsCate',
		'idField'=>'cat_id',
		'htmlOptions'=>array(
			'method'=>'POST',
			'width'=>1250,
			'height'=>630,
		//	'idField'=>'good_id',
			'fitColumns'=>true,
			'nowrap'=>false,
			'rownumbers'=>true,
			'showFooter'=>true,
			'pagination'=>true,
			'rownumbers'=>false,
                        'singleSelect'=>false,
		),
		'toolbar_show'=>array(
			'add'=>array('href'=>Yii::app()->createUrl('webshop/goodscate/create'),'text'=>'添加商品分类'),
			'delete'=>array('href'=>Yii::app()->createUrl('webshop/goodscate/delete'),'text'=>'删除商品分类'),
			'edit'=>array('href'=>Yii::app()->createUrl('webshop/goodscate/update')),
			'view'=>array('href'=>Yii::app()->createUrl('webshop/goodscate/view')),
			'search'=>array('href'=>Yii::app()->createUrl('webshop/goodscate/loadData'),'text'=>'搜索商品分类','formTpl'=>'searchGoodsCate'),
                        'multiple'=>array('href'=>Yii::app()->createUrl('webshop/goodscate/updateBatch'),'text'=>'批量更改','formTpl'=>'multipleGoodsCate'),
		),
		'columns'=>array(
                        array('field'=>'cat_id','title'=>Yii::t('webshop',GoodsCate::model()->getAttributeLabel('cat_id')),'width'=>80,'checkbox'=>true),
                      //  array('field'=>'good_id','title'=>Yii::t('webshop',Goods::model()->getAttributeLabel('good_id')),'width'=>80),
			array('field'=>'cat_name','title'=>Yii::t('webshop',GoodsCate::model()->getAttributeLabel('cat_name')),'width'=>200,'search'=>true),
                        array('field'=>'cat_desc','title'=>Yii::t('webshop',GoodsCate::model()->getAttributeLabel('cat_desc')),'width'=>80,'search'=>true),
                        array('field'=>'parent_id','title'=>Yii::t('webshop',GoodsCate::model()->getAttributeLabel('parent_id')),'width'=>80,'search'=>true),
                        array('field'=>'sort_order','title'=>Yii::t('webshop',GoodsCate::model()->getAttributeLabel('sort_order')),'width'=>80,'search'=>true),
                        array('field'=>'level','title'=>Yii::t('webshop',GoodsCate::model()->getAttributeLabel('level')),'width'=>80,'search'=>true),
		),
	));?>

