<?php $this->widget('ext.easyui.EasyuiGrid',array(
		'title'=>Yii::t('project','List Brands'),
		'url'=>Yii::app()->createUrl('brand/loadData'),
		'model'=>'Brand',
		'idField'=>'brand_id',
		'htmlOptions'=>array(
			'method'=>'POST',
			'width'=>1250,
			'height'=>630,
		//	'idField'=>'good_id',
			'fitColumns'=>true,
			'nowrap'=>false,
			'rownumbers'=>true,
			'showFooter'=>true,
			'pagination'=>true,
			'rownumbers'=>false,
                        'singleSelect'=>false,
		),
		'toolbar_show'=>array(
			'add'=>array('href'=>Yii::app()->createUrl('brand/create'),'text'=>'添加品牌'),
			'delete'=>array('href'=>Yii::app()->createUrl('brand/delete'),'text'=>'删除品牌'),
			'edit'=>array('href'=>Yii::app()->createUrl('brand/update')),
			'view'=>array('href'=>Yii::app()->createUrl('brand/view')),
			'search'=>array('href'=>Yii::app()->createUrl('brand/loadData'),'text'=>'搜索品牌','formTpl'=>'searchBrand'),
                        'multiple'=>array('href'=>Yii::app()->createUrl('brand/updateBatch'),'text'=>'批量更改','formTpl'=>'multipleBrand'),
		),
		'columns'=>array(
                        array('field'=>'brand_id','title'=>Yii::t('project',Brand::model()->getAttributeLabel('brand_id')),'width'=>80,'checkbox'=>true),
                      //  array('field'=>'good_id','title'=>Yii::t('webshop',Goods::model()->getAttributeLabel('good_id')),'width'=>80),
			array('field'=>'brand_name','title'=>Yii::t('project',Brand::model()->getAttributeLabel('brand_name')),'width'=>100,'search'=>true),
                        array('field'=>'cat_id','title'=>Yii::t('project',Brand::model()->getAttributeLabel('cat_id')),'width'=>80,'search'=>true),
                        array('field'=>'brand_alia','title'=>Yii::t('project',Brand::model()->getAttributeLabel('brand_alia')),'width'=>30,'search'=>true),
                        array('field'=>'brand_location','title'=>Yii::t('project',Brand::model()->getAttributeLabel('brand_location')),'width'=>100,'search'=>true),
                        array('field'=>'in_shop','title'=>Yii::t('project',Brand::model()->getAttributeLabel('in_shop')),'width'=>30,'search'=>true),
		),
	));?>
