<?php $this->widget('ext.easyui.EasyuiGrid',array(
		'title'=>Yii::t('project','List Issues'),
		'url'=>Yii::app()->createUrl('issues/loadData'),
		'model'=>'Issues',
		'idField'=>'id',
		'htmlOptions'=>array(
			'method'=>'POST',
			'width'=>1250,
			'height'=>630,
		//	'idField'=>'good_id',
			'fitColumns'=>true,
			'nowrap'=>false,
			'rownumbers'=>true,
			'showFooter'=>true,
			'pagination'=>true,
			'rownumbers'=>false,
                        'singleSelect'=>false,
		),
		'toolbar_show'=>array(
			'add'=>array('href'=>Yii::app()->createUrl('issues/create'),'text'=>'添加错误异常'),
			'delete'=>array('href'=>Yii::app()->createUrl('issues/delete'),'text'=>'删除错误异常'),
			'edit'=>array('href'=>Yii::app()->createUrl('issues/update')),
			'view'=>array('href'=>Yii::app()->createUrl('issues/view')),
			'search'=>array('href'=>Yii::app()->createUrl('issues/loadData'),'text'=>'搜索错误异常','formTpl'=>'searchIssues'),
                 //       'multiple'=>array('href'=>Yii::app()->createUrl('issues/updateBatch'),'text'=>'批量更改','formTpl'=>'multipleIssues'),
		),
		'columns'=>array(
                        array('field'=>'id','title'=>Yii::t('project',Issues::model()->getAttributeLabel('id')),'width'=>80,'checkbox'=>true),
                      //  array('field'=>'good_id','title'=>Yii::t('webshop',Goods::model()->getAttributeLabel('good_id')),'width'=>80),
			array('field'=>'title','title'=>Yii::t('project',Issues::model()->getAttributeLabel('title')),'width'=>100,'search'=>true),
                        array('field'=>'add_time','title'=>Yii::t('project',Issues::model()->getAttributeLabel('add_time')),'width'=>80,'search'=>true),
                        array('field'=>'update_time','title'=>Yii::t('project',Issues::model()->getAttributeLabel('update_time')),'width'=>30,'search'=>true),
                        array('field'=>'user_id','title'=>Yii::t('project',Issues::model()->getAttributeLabel('user_id')),'width'=>100,'search'=>true),
                        array('field'=>'finished','title'=>Yii::t('project',Issues::model()->getAttributeLabel('finished')),'width'=>30,'search'=>true),
		),
	));?>
